In [46]:
#Вкладчик положил 50000 условных единиц на три разных счета в три разных банка. По первому счету выплаты составят 5% годовых,
#по второму – 7% годовых и по третьему 6% годовых. Известно, что через год вкладчик получил по процентам сумму в 2250 у.е.
#с первого и второго банка и сумму в 1400 у.е. с первого и третьего банка. Сколько условных единиц он положил на каждый счет
#изначально?


import numpy as np

a = np.matrix("0.05,0.07;0.01,0.06")
b = np.matrix("2250;1600")
a_inv = np.linalg.inv(a)
x = a_inv.dot(b)
print(f'В перший банк вкладник поклав {x[0]} у.о, у другий {50000-x[0]-x[1]} y.o, у третій {x[1]} y.o')

В перший банк вкладник поклав [[10000.]] у.о, у другий [[15000.]] y.o, у третій [[25000.]] y.o


In [2]:
#На складе хранятся мобильные телефоны iPhone 6, iPhone 11, iPhone 12 моделей. Всего 1328 экземпляра.
#Моделей iPhone 6 на 120 меньше, чем моделей iPhone 11, и на 100 больше, чем моделей iPhone 12.
#Сколько моделей каждого вида на складе?


import numpy as np

a = np.array([[1,1,1],[1,-1,0],[1,0,-1]])
b = np.array([1328,-120,100])
x = np.linalg.inv(a).dot(b)
print(x)

[436. 556. 336.]


In [4]:
#Составьте каноническое уравнение эллипсоида, проходящего через три точки A,B,C

import numpy as np

a = np.matrix("3,0,3;6,0.25,0;1,0.33,1")
b = np.matrix("1;1;1")
x = np.linalg.solve(a, b)
print(x)

[[0.08249158]
 [2.02020202]
 [0.25084175]]


In [62]:
#Составьте уравнение параболы проходящей через заданные три точки (1,12), (3,54), (-1,2).
#Необходимо найти коэффициенты уравнения a,b,c


import numpy as np

a = np.matrix("1,1,1;9,3,1;1,-1,1")
b = np.matrix("12;54;2")
x = np.linalg.solve(a, b)
print(x)

[[4.]
 [5.]
 [3.]]


In [3]:
#Составьте функцию get_polynom

import numpy as np


def get_polynom(coords):
    a = []
    b = []
    for x, y in coords:
        row = []
        b.append(y)
        for i in range(len(coords)):
            row.append(x ** i)
        a.append(row)
    return np.linalg.solve(a, b).astype('int')

print(get_polynom([(1,2), (3,4)]))


[1 1]
