In [1]:
pip install sklearn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


In [2]:
from sklearn.datasets import load_wine

wine_dataset = load_wine()
wine_dataset.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names'])

In [3]:
x = wine_dataset.data
y = wine_dataset.target

In [4]:
print(x.shape)
print(y.shape)

(178, 13)
(178,)


In [5]:

import numpy as np

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split


from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

from sklearn.model_selection import cross_val_score

In [6]:
log = LogisticRegression(solver='lbfgs', max_iter=5000)
results = cross_val_score(log, x, y, cv=5)

In [7]:

mean = np.mean(results)
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=38)
log.fit(X_train, y_train)
y_pred = log.predict(X_test)

In [8]:
y_pred

array([2, 0, 0, 0, 1, 2, 2, 1, 2, 0, 0, 1, 0, 2, 1, 0, 0, 1, 2, 1, 0, 0,
       1, 0, 2, 1, 1, 0, 2, 0, 0, 1, 2, 1, 1, 1, 1, 0, 0, 2, 0, 1, 0, 1,
       1, 1, 1, 2, 1, 0, 1, 0, 2, 2])

In [9]:
y_test

array([2, 0, 0, 0, 1, 2, 2, 1, 2, 0, 0, 1, 0, 2, 1, 0, 0, 1, 2, 1, 0, 1,
       2, 0, 2, 1, 1, 0, 2, 0, 0, 1, 2, 1, 1, 1, 1, 0, 0, 2, 0, 1, 0, 1,
       1, 1, 1, 2, 2, 0, 1, 0, 2, 2])

In [10]:
log.score(X_test, y_test)

0.9444444444444444

In [11]:
confusion_matrix(y_pred, y_test)

array([[19,  1,  0],
       [ 0, 19,  2],
       [ 0,  0, 13]])

In [12]:
print(classification_report(y_pred, y_test))

              precision    recall  f1-score   support

           0       1.00      0.95      0.97        20
           1       0.95      0.90      0.93        21
           2       0.87      1.00      0.93        13

    accuracy                           0.94        54
   macro avg       0.94      0.95      0.94        54
weighted avg       0.95      0.94      0.94        54

